### ISSUE TITLE
Incorrect Info Tooltip

### ISSUE THREAD

**Issue by astraldragon** [Atelier-Shiori/Shukofukurou#13]
Tooltip for info icon says View on Myanimelist when viewing a Kitsu entry.

<img width="605" alt="screen shot 2018-06-01 at 9 17 30 pm" src="https://user-images.githubusercontent.com/846931/40868242-61766776-65e1-11e8-84a0-ef56927fe3e4.png">

**Comment by moyitpro** [comment]
Will fix in the next release

**Comment by moyitpro** [comment]
Fixed with https://github.com/Atelier-Shiori/Shukofukurou/commit/ce5022c847f254f05364df62937ae9d31167dc84
