### ISSUE TITLE
Exporting hangs

### ISSUE THREAD

**Issue by matthewdias** [Atelier-Shiori/Shukofukurou#14]
Trying to convert my Kitsu anime list for export, and it's stuck at 55%. I've tried quitting the app and restarting the export, but it just resumes and gets stuck at the same place.

**Comment by moyitpro** [comment]
I haven't tested the export with large lists, but I will take a look at it. Since your list is large, it will take a while. I will add a cancel button once I figure out the issue.

**Comment by moyitpro** [comment]
I committed a fix and loaded your list by overriding and it seems to work. I want to make sure it works on your side. I attached a potential fix. Try this and reply back if it works or not.

[Shukofukurou.app.zip](https://github.com/Atelier-Shiori/Shukofukurou/files/2100508/Shukofukurou.app.zip)

**Comment by matthewdias** [comment]
Works 👍
