### ISSUE TITLE
Crash on MAL manga list import to Kitsu

### ISSUE THREAD

**Issue by fieldhouse** [Atelier-Shiori/Shukofukurou#16]
I recently grabbed my anime and manga exports from MAL.  Anime imported to Kitsu fine (took forever, but it was 1.6 MB).  Manga import to Kitsu crashes Shukofukurou consistently around 65%.  I narrowed it down to one specific manga entry in the XML (dump output and zipped xml attached for your viewing pleasure).  Import of this entry to AniList does not crash.  
[crash dump.txt](https://github.com/Atelier-Shiori/Shukofukurou/files/2108339/crash.dump.txt)

No complaints, just figured I should let you know since it's a consistent crash.
[mangalist_1528781453_-_467081-26th.a.1 32 (crashes shukofukurou on import).xml.zip](https://github.com/Atelier-Shiori/Shukofukurou/files/2108325/mangalist_1528781453_-_467081-26th.a.1.32.crashes.shukofukurou.on.import.xml.zip)

**Comment by moyitpro** [comment]
I have found this bug out and it seems that in some cases when the program tries to find the title id using the title, there are nulls and I needed to add checks for them. I added a check so it won't be an issue.

https://github.com/Atelier-Shiori/Shukofukurou/commit/237032249404e909d913956ae152e7762478edfd

I can provide a build with that commit if you want to test it out.

**Comment by fieldhouse** [comment]
Totally up to you.  Sounds like a straightforward fix.   I can test it once my anime import to AniList finishes. It's at 58% now after 3 hours so it'll be a while :)

**Comment by moyitpro** [comment]
Release 3.0.7 fixes this issue, hopefully. Closing this issue.

**Comment by fieldhouse** [comment]
Confirmed.  3.0.7 fixes the crash.
