### ISSUE TITLE
Suggestion: Add service name to login status line

### ISSUE THREAD

**Issue by fieldhouse** [Atelier-Shiori/Shukofukurou#17]
**Logged in as -username- ** doesn't help when a user's login name is the same on both Kitsu and AniList.  I suggest changing it to -service-:-username- or "Logged into <service> as <username>

![image](https://user-images.githubusercontent.com/2186295/41606612-ee012b12-7398-11e8-9c93-613316ffe6d0.png)

**Comment by moyitpro** [comment]
Fixed with https://github.com/Atelier-Shiori/Shukofukurou/commit/dfff8334e04a1f4d4025922e2fb8c6683e7bc538
