### ISSUE TITLE
How to import manga from kitsu to anilist

### ISSUE THREAD

**Issue by Glistentae** [Atelier-Shiori/Shukofukurou#26]
I've noticed that when I click import from kitsu, only the anime gets imported and not the mangas.
is there a way which I didn't notice?

**Comment by moyitpro** [comment]
There is no option to import from Kitsu to AniList yet. The only obvious way is to export the converted XML and import that as a MyAnimeList XML import on AniList. List syncing will be added in the future, which will give similar functionality to this.

**Comment by Glistentae** [comment]
Well, I bought this software for that purpose.

**Comment by moyitpro** [comment]
It will be a while before we have sync functionality between services. If you want a refund, send me an email to james_moy@moyit.pro with the order reference number. If you decide to refund, you must uninstall the software and provide proof that you did through a screenshot (the app needs to be in free version mode) the license key will be invalidated in future releases.
