### ISSUE TITLE
more order option (by airing season, date of adding, ...)

### ISSUE THREAD

**Issue by LoosGuccreen** [Atelier-Shiori/Shukofukurou#34]
It would be great to be able to have a list ordered by airing season (and other order such as when we added it on our list, stuff like that). 

When I'm on Windows I use Taiga that has this feature and it would be really cool to have it on Shukofukurou (since I'm more often on my mac...)

I don't know exactly what to say more than this lol. Thanks for having made this soft by the way it's very useful 👍

**Comment by moyitpro** [comment]
Implemented with 3.6 (prerelease)

https://github.com/Atelier-Shiori/Shukofukurou/commit/71587bd037d9690a309560778c3c858cfa0ee776
