### ISSUE TITLE
Universal Binary for Apple Silicon

### ISSUE THREAD

**Issue by thebitstick** [Atelier-Shiori/Shukofukurou#35]
Shukofukurou works great under Rosetta, but a native binary would be nice!

**Comment by moyitpro** [comment]
There is already a Universal Binary version, but it’s currently for active Patrons.The public beta with universal binary is coming mid December.

**Comment by thebitstick** [comment]
Even though I purchased the app through the App Store?

**Comment by moyitpro** [comment]
Yes, the next 3.x release with Universal Binary support will be a free update and available on the App Store. The beta version is able to unlock with the App Store release once the public beta is released.

**Comment by moyitpro** [comment]
The first beta of Shukofukurou for macOS 3.5 is now out with Universal Binary 2 support.

https://github.com/Atelier-Shiori/Shukofukurou/releases/tag/3.5-beta1
