### ISSUE TITLE
Requesting a refresh under the "Manga List" tab crashes the application

### ISSUE THREAD

**Issue by vincentcomfy** [Atelier-Shiori/Shukofukurou#40]
As the title suggests, either pressing the refresh button, adding a new item to the list or trying to increment an existing item will cause the app to crash to desktop. Was not happening prior to the release of 3.5.3.

**Comment by moyitpro** [comment]
It's a big oopsie. When I updated the backend framework that handles the API  for all the services, I forgot that there were new fields in the data model that needed to be added, which is causing the crashing issue. This has been fixed and a release will come out shortly on the App Store.
